== Звіт за практичну роботу №2. Перетворення кольорів.

Автор: Ясногородський Нікіта Вікторович, ТУ-12-22-Б1ІПЗ

У цьому звіті будуть наведені результати виконання практичної роботи №2 на тему "Перетворення кольорів". Під час цієї роботи ми вивчали різні формати кольорів, такі як HEX, RGB, HSL, CMYK, HSB, а також виконували їх взаємне перетворення.

== Хід роботи

[cols="6",options="header"]
|===
| Input color | HEX | RGB | HSL | CMYK | HSB
| #94519e | #94519e | RGB(148, 81, 158) | HSL(292°, 32%, 47%) | CMYK(6%, 49%, 0%, 38%) | HSB(292°, 49%, 62%)
| #c9ffe1 | #c9ffe1 | RGB(201, 255, 225) | HSL(149°, 100%, 89%) | CMYK(21%, 0%, 12%, 0%) | HSB(149°, 21%, 100%)
| #94519e | #94519e | RGB(148, 81, 158) | HSL(292°, 32%, 47%) | CMYK(6%, 49%, 0%, 38%) | HSB(292°, 49%, 62%)
| hsl(147, 100%, 89%) | #dfffff | RGB(223, 255, 223) | HSL(147°, 100%, 89%) | CMYK(13%, 0%, 13%, 0%) | HSB(147°, 13%, 100%)
| CMYK(0%, 100%, 100%, 1%) | #ff0000 | RGB(255, 0, 0) | - | CMYK(0%, 100%, 100%, 1%) | HSB(0°, 100%, 100%)
|===

=== Висновок

Під час виконання практичної роботи було успішно виконано перетворення кольорів між форматами HEX, RGB, HSL, CMYK та HSB. Використання цих різних форматів дозволяє ефективно працювати з кольорами та здійснювати їх конвертацію в різноманітні формати для потреб різних програм та проектів.
