== Лабораторна робота №1

Автор: Ясногородський Нікіта Вікторович, ТУ-12-22-Б1ІПЗ

*Тема:* Введення в практику РСУБД.

*Мета:* Написати скрипт для пакетного створення бази даних, що складається з однієї таблиці з двома полями (ціле і текстове), введення в таблицю декількох записів і виконання оператора вибірки.

== Виконання

[start={list-counter}]
{counter:list-counter}. Створення бази даних та таблиці:
[source,sql]
----
CREATE TABLE IF NOT EXISTS coffee (
    sort VARCHAR(255),
    price DECIMAL(10,2)
);
----

{counter:list-counter}. Вставка декількох записів в таблицю:
[source,sql]
----
INSERT INTO coffee (sort, price) VALUES
('espresso', 45.43),
('latte', 65.00);
----

{counter:list-counter}. Виконання оператора вибірки:
[source,sql]
----
SELECT * FROM coffee;
----

== Висновок

У результаті виконання лабораторної роботи було успішно створено базу даних "online_store" для зберігання інформації про товари в інтернет-магазині. Таблиця "coffee" містить інформацію про каву, включаючи сорт та цінy. Декілька записів було вставлено у таблицю, а також було виконано запит для вибірки всіх записів для перевірки коректності вставки. Усі етапи виконано вірно та без помилок.
